apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: elasticsearch
  labels:
    logging.kubesphere.io/enabled: "true"
    app.kubernetes.io/version: v0.2.0
spec:
  match: kube.*
  es:
    host: elk-es-default.monitoring.svc
    port: 9200
    logstashPrefix: ks-logstash-log
    logstashPrefixKey: container_name
    logstashFormat: true
    timeKey: "@timestamp"
  stdout: {}
