apiVersion: v1
kind: ServiceAccount
metadata:
  name: weave-scope
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "original-request": {
          "url": "/k8s/v1.13/scope.yaml",
          "date": "Sun Sep 06 2020 16:57:02 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
  labels:
    name: weave-scope
  namespace: weave
