metadata:
  name: istio-operator
  namespace: istio-operator
spec:
  source:
    repoURL: https://github.com/dorroddorrod/k8s.git
    path: infra/networking/service-mesh/istio/base
  syncPolicy:
    automated:
      prune: false
      selfHeal: false