apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elastic-exporter
  labels:
    k8s-app: app
spec:
  selector:
    matchLabels:
      app: elastic-exporter
  endpoints:
    - port: web
