metadata:
  name: argo-cd
  namespace: cd
spec:
  source:
    repoURL: https://github.com/dorroddorrod/k8s.git
    path: infra/continuous-delivery/argo-cd/base
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  destination:
    server: https://kubernetes123.default.svc
server:
  extraArgs:
    - --insecure