apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy-tracing
  labels:
    app: example-app-tracing
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      app: example-app-tracing
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app-tracing
        facility: kuku
    spec:
      containers:
        - name: example-app-tracing
          image: jaegertracing/example-hotrod:1.19
          imagePullPolicy: Always
          resources:
            requests:
              memory: "50Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "2000m"
