apiVersion: v1
kind: Namespace
metadata:
  name: weave
  annotations:
    cloud.weave.works/version: v1.0.0-282-g0d7359d
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: example
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cd
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas
---
apiVersion: v1
kind: Namespace
metadata:
  name: openfaas-fn
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-operator
  labels:
    istio-operator-managed: Reconcile
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-rollouts-ben

