apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weave-scope
  namespace: cd
spec:
  project: default
  source:
    repoURL: https://github.com/dorroddorrod/k8s.git
    targetRevision: HEAD
    path: infra/visibility/weave-scope
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: weave
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
