apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - horizontal_pod_autoscaler.yaml
  - ingress.yaml
  - service_monitor.yaml