apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfaas-operator-rw
  namespace: "openfaas-fn"
  labels:
    app: openfaas
    component: openfaas-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openfaas-operator-rw
subjects:
  - kind: ServiceAccount
    name: openfaas-operator
    namespace: "openfaas"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfaas-prometheus
  namespace: "openfaas"
  labels:
    app: openfaas
    component: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openfaas-prometheus
subjects:
  - kind: ServiceAccount
    name: openfaas-prometheus
    namespace: "openfaas"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfaas-prometheus
  namespace: "openfaas-fn"
  labels:
    app: openfaas
    component: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openfaas-prometheus
subjects:
  - kind: ServiceAccount
    name: openfaas-prometheus
    namespace: "openfaas"
