apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfaas-operator-rw
  namespace: "openfaas-fn"
  labels:
    app: openfaas
    component: openfaas-operator
rules:
  - apiGroups: ["openfaas.com"]
    resources: ["functions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "namespaces", "endpoints"]
    verbs: ["get", "list", "watch"]
