apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfaas-operator
  namespace: "openfaas"
  labels:
    app: openfaas
    component: openfaas-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openfaas-prometheus
  namespace: "openfaas"
  labels:
    app: openfaas
    component: prometheus
