apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-operator-metrics
  labels:
    k8s-app: app
spec:
  selector:
    matchLabels:
      app: grafana-operator-metrics
  endpoints:
    - port: http-metrics
