apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elk-operator
  namespace: cd
spec:
  project: default
  source:
    repoURL: https://github.com/dorroddorrod/k8s.git
    targetRevision: HEAD
    path: infra/visibility/elk-operator
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  ignoreDifferences:
    - group: beats.beat.k8s.elastic.co
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec
    - group: elastic-webhook.k8s.elastic.co
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/clientConfig/caBundle
