apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  profile: minimal
  values:
    global:
      tracer:
        zipkin:
          address: simple-prod-collector.monitoring.svc:9411
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 100
