apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app-istio
  namespace: cd
spec:
  project: default
  source:
    repoURL: https://github.com/dorroddorrod/k8s.git
    targetRevision: HEAD
    path: applications/example-app-istio
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
