apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/deployment.yaml
  - ../../base/service.yaml
  - ../../base/configmap.yaml
  - ../../base/horizontal_pod_autoscaler.yaml
  - ../../base/ingress.yaml
  - ../../base/service_monitor.yaml