apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.metadata.name }}
  namespace: cd
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: {{ .Values.spec.source.path }}
    helm:
      valueFiles:
        - values.yaml
        - ../overlays/dev/values.yaml
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.spec.destination.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.spec.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}
