apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.metadata.name }}
  namespace: cd
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: {{ .Values.spec.source.path }}
    helm:
      valueFiles:
        - values.yaml
        - "../overlays/{{ .Values.metadata.env }}/values.yaml"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.spec.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}
