apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-metrics
  labels:
    k8s-app: app
spec:
  selector:
    matchLabels:
      name: jaeger-operator
  endpoints:
    - port: http-metrics
