apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: cd
spec:
  project: default
  source:
    repoURL: { { .Values.spec.source.repoURL } }
    targetRevision: { { .Values.spec.source.targetRevision } }
    path: { { .Values.spec.source.path } }
    directory:
      recurse: false
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.spec.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}
