apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: cd
spec:
  project: default
  source:
    repoURL: https://github.com/dorroddorrod/k8s.git
    targetRevision: HEAD
    path: infra/continuous-delivery/argo-cd
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: example
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
