apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grafana-exporter
  labels:
    k8s-app: app
spec:
  selector:
    matchLabels:
      app: grafana-service
  endpoints:
    - port: grafana
